export const PHONE_COUNTRY_OPTIONS = [
  { code: "af", iso: "AF", label: "Afghanistan", dialCode: "+93" },
  { code: "al", iso: "AL", label: "Albania", dialCode: "+355" },
  { code: "dz", iso: "DZ", label: "Algeria", dialCode: "+213" },
  { code: "ad", iso: "AD", label: "Andorra", dialCode: "+376" },
  { code: "ao", iso: "AO", label: "Angola", dialCode: "+244" },
  { code: "ag", iso: "AG", label: "Antigua and Barbuda", dialCode: "+1-268" },
  { code: "ar", iso: "AR", label: "Argentina", dialCode: "+54" },
  { code: "am", iso: "AM", label: "Armenia", dialCode: "+374" },
  { code: "au", iso: "AU", label: "Australia", dialCode: "+61" },
  { code: "at", iso: "AT", label: "Austria", dialCode: "+43" },
  { code: "az", iso: "AZ", label: "Azerbaijan", dialCode: "+994", localLength: 9, placeholder: "50 123 45 67" },
  { code: "bs", iso: "BS", label: "Bahamas", dialCode: "+1-242" },
  { code: "bh", iso: "BH", label: "Bahrain", dialCode: "+973" },
  { code: "bd", iso: "BD", label: "Bangladesh", dialCode: "+880" },
  { code: "bb", iso: "BB", label: "Barbados", dialCode: "+1-246" },
  { code: "by", iso: "BY", label: "Belarus", dialCode: "+375" },
  { code: "be", iso: "BE", label: "Belgium", dialCode: "+32" },
  { code: "bz", iso: "BZ", label: "Belize", dialCode: "+501" },
  { code: "bj", iso: "BJ", label: "Benin", dialCode: "+229" },
  { code: "bt", iso: "BT", label: "Bhutan", dialCode: "+975" },
  { code: "bo", iso: "BO", label: "Bolivia", dialCode: "+591" },
  { code: "ba", iso: "BA", label: "Bosnia and Herzegovina", dialCode: "+387" },
  { code: "bw", iso: "BW", label: "Botswana", dialCode: "+267" },
  { code: "br", iso: "BR", label: "Brazil", dialCode: "+55" },
  { code: "bn", iso: "BN", label: "Brunei", dialCode: "+673" },
  { code: "bg", iso: "BG", label: "Bulgaria", dialCode: "+359" },
  { code: "bf", iso: "BF", label: "Burkina Faso", dialCode: "+226" },
  { code: "bi", iso: "BI", label: "Burundi", dialCode: "+257" },
  { code: "kh", iso: "KH", label: "Cambodia", dialCode: "+855" },
  { code: "cm", iso: "CM", label: "Cameroon", dialCode: "+237" },
  { code: "ca", iso: "CA", label: "Canada", dialCode: "+1" },
  { code: "cv", iso: "CV", label: "Cape Verde", dialCode: "+238" },
  { code: "cf", iso: "CF", label: "Central African Republic", dialCode: "+236" },
  { code: "td", iso: "TD", label: "Chad", dialCode: "+235" },
  { code: "cl", iso: "CL", label: "Chile", dialCode: "+56" },
  { code: "cn", iso: "CN", label: "China", dialCode: "+86" },
  { code: "co", iso: "CO", label: "Colombia", dialCode: "+57" },
  { code: "km", iso: "KM", label: "Comoros", dialCode: "+269" },
  { code: "cg", iso: "CG", label: "Congo", dialCode: "+242" },
  { code: "cd", iso: "CD", label: "Congo (DRC)", dialCode: "+243" },
  { code: "cr", iso: "CR", label: "Costa Rica", dialCode: "+506" },
  { code: "ci", iso: "CI", label: "Côte d’Ivoire", dialCode: "+225" },
  { code: "hr", iso: "HR", label: "Croatia", dialCode: "+385" },
  { code: "cu", iso: "CU", label: "Cuba", dialCode: "+53" },
  { code: "cy", iso: "CY", label: "Cyprus", dialCode: "+357" },
  { code: "cz", iso: "CZ", label: "Czech Republic", dialCode: "+420" },
  { code: "dk", iso: "DK", label: "Denmark", dialCode: "+45" },
  { code: "dj", iso: "DJ", label: "Djibouti", dialCode: "+253" },
  { code: "dm", iso: "DM", label: "Dominica", dialCode: "+1-767" },
  { code: "do", iso: "DO", label: "Dominican Republic", dialCode: "+1-809" },
  { code: "ec", iso: "EC", label: "Ecuador", dialCode: "+593" },
  { code: "eg", iso: "EG", label: "Egypt", dialCode: "+20" },
  { code: "sv", iso: "SV", label: "El Salvador", dialCode: "+503" },
  { code: "gq", iso: "GQ", label: "Equatorial Guinea", dialCode: "+240" },
  { code: "er", iso: "ER", label: "Eritrea", dialCode: "+291" },
  { code: "ee", iso: "EE", label: "Estonia", dialCode: "+372" },
  { code: "sz", iso: "SZ", label: "Eswatini", dialCode: "+268" },
  { code: "et", iso: "ET", label: "Ethiopia", dialCode: "+251" },
  { code: "fj", iso: "FJ", label: "Fiji", dialCode: "+679" },
  { code: "fi", iso: "FI", label: "Finland", dialCode: "+358" },
  { code: "fr", iso: "FR", label: "France", dialCode: "+33", localLength: 9, placeholder: "6 12 34 56 78" },
  { code: "ga", iso: "GA", label: "Gabon", dialCode: "+241" },
  { code: "gm", iso: "GM", label: "Gambia", dialCode: "+220" },
  { code: "ge", iso: "GE", label: "Georgia", dialCode: "+995", localLength: 9, placeholder: "555 12 34 56" },
  { code: "de", iso: "DE", label: "Germany", dialCode: "+49", minLength: 10, maxLength: 11, placeholder: "1512 3456789" },
  { code: "gh", iso: "GH", label: "Ghana", dialCode: "+233" },
  { code: "gr", iso: "GR", label: "Greece", dialCode: "+30" },
  { code: "gd", iso: "GD", label: "Grenada", dialCode: "+1-473" },
  { code: "gt", iso: "GT", label: "Guatemala", dialCode: "+502" },
  { code: "gn", iso: "GN", label: "Guinea", dialCode: "+224" },
  { code: "gw", iso: "GW", label: "Guinea-Bissau", dialCode: "+245" },
  { code: "gy", iso: "GY", label: "Guyana", dialCode: "+592" },
  { code: "ht", iso: "HT", label: "Haiti", dialCode: "+509" },
  { code: "hn", iso: "HN", label: "Honduras", dialCode: "+504" },
  { code: "hu", iso: "HU", label: "Hungary", dialCode: "+36" },
  { code: "is", iso: "IS", label: "Iceland", dialCode: "+354" },
  { code: "in", iso: "IN", label: "India", dialCode: "+91" },
  { code: "id", iso: "ID", label: "Indonesia", dialCode: "+62" },
  { code: "ir", iso: "IR", label: "Iran", dialCode: "+98" },
  { code: "iq", iso: "IQ", label: "Iraq", dialCode: "+964" },
  { code: "ie", iso: "IE", label: "Ireland", dialCode: "+353" },
  { code: "il", iso: "IL", label: "Israel", dialCode: "+972" },
  { code: "it", iso: "IT", label: "Italy", dialCode: "+39", localLength: 10, placeholder: "312 345 6789" },
  { code: "jm", iso: "JM", label: "Jamaica", dialCode: "+1-876" },
  { code: "jp", iso: "JP", label: "Japan", dialCode: "+81" },
  { code: "jo", iso: "JO", label: "Jordan", dialCode: "+962" },
  { code: "kz", iso: "KZ", label: "Kazakhstan", dialCode: "+7-6" },
  { code: "ke", iso: "KE", label: "Kenya", dialCode: "+254" },
  { code: "ki", iso: "KI", label: "Kiribati", dialCode: "+686" },
  { code: "xk", iso: "XK", label: "Kosovo", dialCode: "+383" },
  { code: "kw", iso: "KW", label: "Kuwait", dialCode: "+965" },
  { code: "kg", iso: "KG", label: "Kyrgyzstan", dialCode: "+996" },
  { code: "la", iso: "LA", label: "Laos", dialCode: "+856" },
  { code: "lv", iso: "LV", label: "Latvia", dialCode: "+371" },
  { code: "lb", iso: "LB", label: "Lebanon", dialCode: "+961" },
  { code: "ls", iso: "LS", label: "Lesotho", dialCode: "+266" },
  { code: "lr", iso: "LR", label: "Liberia", dialCode: "+231" },
  { code: "ly", iso: "LY", label: "Libya", dialCode: "+218" },
  { code: "li", iso: "LI", label: "Liechtenstein", dialCode: "+423" },
  { code: "lt", iso: "LT", label: "Lithuania", dialCode: "+370" },
  { code: "lu", iso: "LU", label: "Luxembourg", dialCode: "+352" },
  { code: "mg", iso: "MG", label: "Madagascar", dialCode: "+261" },
  { code: "mw", iso: "MW", label: "Malawi", dialCode: "+265" },
  { code: "my", iso: "MY", label: "Malaysia", dialCode: "+60" },
  { code: "mv", iso: "MV", label: "Maldives", dialCode: "+960" },
  { code: "ml", iso: "ML", label: "Mali", dialCode: "+223" },
  { code: "mt", iso: "MT", label: "Malta", dialCode: "+356" },
  { code: "mh", iso: "MH", label: "Marshall Islands", dialCode: "+692" },
  { code: "mr", iso: "MR", label: "Mauritania", dialCode: "+222" },
  { code: "mu", iso: "MU", label: "Mauritius", dialCode: "+230" },
  { code: "mx", iso: "MX", label: "Mexico", dialCode: "+52" },
  { code: "fm", iso: "FM", label: "Micronesia", dialCode: "+691" },
  { code: "md", iso: "MD", label: "Moldova", dialCode: "+373" },
  { code: "mc", iso: "MC", label: "Monaco", dialCode: "+377" },
  { code: "mn", iso: "MN", label: "Mongolia", dialCode: "+976" },
  { code: "me", iso: "ME", label: "Montenegro", dialCode: "+382" },
  { code: "ma", iso: "MA", label: "Morocco", dialCode: "+212" },
  { code: "mz", iso: "MZ", label: "Mozambique", dialCode: "+258" },
  { code: "mm", iso: "MM", label: "Myanmar", dialCode: "+95" },
  { code: "na", iso: "NA", label: "Namibia", dialCode: "+264" },
  { code: "nr", iso: "NR", label: "Nauru", dialCode: "+674" },
  { code: "np", iso: "NP", label: "Nepal", dialCode: "+977" },
  { code: "nl", iso: "NL", label: "Netherlands", dialCode: "+31" },
  { code: "nz", iso: "NZ", label: "New Zealand", dialCode: "+64" },
  { code: "ni", iso: "NI", label: "Nicaragua", dialCode: "+505" },
  { code: "ne", iso: "NE", label: "Niger", dialCode: "+227" },
  { code: "ng", iso: "NG", label: "Nigeria", dialCode: "+234" },
  { code: "kp", iso: "KP", label: "North Korea", dialCode: "+850" },
  { code: "mk", iso: "MK", label: "North Macedonia", dialCode: "+389" },
  { code: "no", iso: "NO", label: "Norway", dialCode: "+47" },
  { code: "om", iso: "OM", label: "Oman", dialCode: "+968" },
  { code: "pk", iso: "PK", label: "Pakistan", dialCode: "+92" },
  { code: "pw", iso: "PW", label: "Palau", dialCode: "+680" },
  { code: "ps", iso: "PS", label: "Palestine", dialCode: "+970" },
  { code: "pa", iso: "PA", label: "Panama", dialCode: "+507" },
  { code: "pg", iso: "PG", label: "Papua New Guinea", dialCode: "+675" },
  { code: "py", iso: "PY", label: "Paraguay", dialCode: "+595" },
  { code: "pe", iso: "PE", label: "Peru", dialCode: "+51" },
  { code: "ph", iso: "PH", label: "Philippines", dialCode: "+63" },
  { code: "pl", iso: "PL", label: "Poland", dialCode: "+48", localLength: 9, placeholder: "512 345 678" },
  { code: "pt", iso: "PT", label: "Portugal", dialCode: "+351", localLength: 9, placeholder: "912 345 678" },
  { code: "qa", iso: "QA", label: "Qatar", dialCode: "+974" },
  { code: "ro", iso: "RO", label: "Romania", dialCode: "+40" },
  { code: "ru", iso: "RU", label: "Russia", dialCode: "+7", localLength: 10, placeholder: "912 345 67 89" },
  { code: "rw", iso: "RW", label: "Rwanda", dialCode: "+250" },
  { code: "kn", iso: "KN", label: "Saint Kitts and Nevis", dialCode: "+1-869" },
  { code: "lc", iso: "LC", label: "Saint Lucia", dialCode: "+1-758" },
  { code: "vc", iso: "VC", label: "Saint Vincent and the Grenadines", dialCode: "+1-784" },
  { code: "ws", iso: "WS", label: "Samoa", dialCode: "+685" },
  { code: "sm", iso: "SM", label: "San Marino", dialCode: "+378" },
  { code: "st", iso: "ST", label: "São Tomé and Príncipe", dialCode: "+239" },
  { code: "sa", iso: "SA", label: "Saudi Arabia", dialCode: "+966" },
  { code: "sn", iso: "SN", label: "Senegal", dialCode: "+221" },
  { code: "rs", iso: "RS", label: "Serbia", dialCode: "+381" },
  { code: "sc", iso: "SC", label: "Seychelles", dialCode: "+248" },
  { code: "sl", iso: "SL", label: "Sierra Leone", dialCode: "+232" },
  { code: "sg", iso: "SG", label: "Singapore", dialCode: "+65" },
  { code: "sk", iso: "SK", label: "Slovakia", dialCode: "+421" },
  { code: "si", iso: "SI", label: "Slovenia", dialCode: "+386" },
  { code: "sb", iso: "SB", label: "Solomon Islands", dialCode: "+677" },
  { code: "so", iso: "SO", label: "Somalia", dialCode: "+252" },
  { code: "za", iso: "ZA", label: "South Africa", dialCode: "+27" },
  { code: "kr", iso: "KR", label: "South Korea", dialCode: "+82" },
  { code: "ss", iso: "SS", label: "South Sudan", dialCode: "+211" },
  { code: "es", iso: "ES", label: "Spain", dialCode: "+34", localLength: 9, placeholder: "612 34 56 78" },
  { code: "lk", iso: "LK", label: "Sri Lanka", dialCode: "+94" },
  { code: "sd", iso: "SD", label: "Sudan", dialCode: "+249" },
  { code: "sr", iso: "SR", label: "Suriname", dialCode: "+597" },
  { code: "se", iso: "SE", label: "Sweden", dialCode: "+46" },
  { code: "ch", iso: "CH", label: "Switzerland", dialCode: "+41" },
  { code: "sy", iso: "SY", label: "Syria", dialCode: "+963" },
  { code: "tw", iso: "TW", label: "Taiwan", dialCode: "+886" },
  { code: "tj", iso: "TJ", label: "Tajikistan", dialCode: "+992" },
  { code: "tz", iso: "TZ", label: "Tanzania", dialCode: "+255" },
  { code: "th", iso: "TH", label: "Thailand", dialCode: "+66" },
  { code: "tl", iso: "TL", label: "Timor-Leste", dialCode: "+670" },
  { code: "tg", iso: "TG", label: "Togo", dialCode: "+228" },
  { code: "to", iso: "TO", label: "Tonga", dialCode: "+676" },
  { code: "tt", iso: "TT", label: "Trinidad and Tobago", dialCode: "+1-868" },
  { code: "tn", iso: "TN", label: "Tunisia", dialCode: "+216" },
  { code: "tr", iso: "TR", label: "Turkey", dialCode: "+90", localLength: 10, placeholder: "532 123 45 67" },
  { code: "tm", iso: "TM", label: "Turkmenistan", dialCode: "+993" },
  { code: "tv", iso: "TV", label: "Tuvalu", dialCode: "+688" },
  { code: "ug", iso: "UG", label: "Uganda", dialCode: "+256" },
  { code: "ua", iso: "UA", label: "Ukraine", dialCode: "+380", localLength: 9, placeholder: "50 123 45 67" },
  { code: "ae", iso: "AE", label: "United Arab Emirates", dialCode: "+971" },
  { code: "gb", iso: "GB", label: "United Kingdom", dialCode: "+44", minLength: 9, maxLength: 10, placeholder: "7400 123456" },
  { code: "us", iso: "US", label: "United States", dialCode: "+1", localLength: 10, placeholder: "202 555 0186" },
  { code: "uy", iso: "UY", label: "Uruguay", dialCode: "+598" },
  { code: "uz", iso: "UZ", label: "Uzbekistan", dialCode: "+998" },
  { code: "vu", iso: "VU", label: "Vanuatu", dialCode: "+678" },
  { code: "va", iso: "VA", label: "Vatican City", dialCode: "+379" },
  { code: "ve", iso: "VE", label: "Venezuela", dialCode: "+58" },
  { code: "vn", iso: "VN", label: "Vietnam", dialCode: "+84" },
  { code: "ye", iso: "YE", label: "Yemen", dialCode: "+967" },
  { code: "zm", iso: "ZM", label: "Zambia", dialCode: "+260" },
  { code: "zw", iso: "ZW", label: "Zimbabwe", dialCode: "+263" },
];

export function getLocalizedCountryName(option, locale) {
  try {
    const displayNames = new Intl.DisplayNames([locale || "en"], { type: "region" });
    return displayNames.of(option.iso) || option.label;
  } catch {
    return option.label;
  }
}
