import {
  Activity,
  BarChart3,
  Briefcase,
  CircleHelp,
  FileText,
  FolderOpen,
  HandCoins,
  LayoutDashboard,
  MessageSquareText,
  Newspaper,
  Settings,
  ShieldCheck,
  SquareCheckBig,
  Users,
  UserSquare2,
  Wallet,
} from "lucide-react";

export const adminNavigation = [
  { label: "Dashboard", path: "/admin", icon: LayoutDashboard, permission: "dashboard.view" },
  { label: "Leads", path: "/admin/leads", icon: UserSquare2, permission: "leads.view" },
  { label: "Cases", path: "/admin/cases", icon: Briefcase, permission: "cases.view" },
  { label: "Customers", path: "/admin/customers", icon: Users, permission: "customers.view" },
  { label: "Tasks", path: "/admin/tasks", icon: SquareCheckBig, permission: "tasks.view" },
  { label: "Communication", path: "/admin/communication", icon: MessageSquareText, permission: "communications.view" },
  { label: "Documents", path: "/admin/documents", icon: FolderOpen, permission: "documents.view" },
  { label: "Referral Partners", path: "/admin/referral-partners", icon: HandCoins, permission: "partners.view" },
  { label: "Finance", path: "/admin/finance", icon: Wallet, permission: "finance.view" },
  { label: "Reports", path: "/admin/reports", icon: BarChart3, permission: "reports.view" },
  { label: "Website CMS", path: "/admin/cms", icon: FileText, permission: "cms.view" },
  { label: "Blog", path: "/admin/blog", icon: Newspaper, permission: "blog.view" },
  { label: "FAQ", path: "/admin/faq", icon: CircleHelp, permission: "faq.view" },
  { label: "Users & Roles", path: "/admin/access", icon: ShieldCheck, permission: "users.view" },
  { label: "Settings", path: "/admin/settings", icon: Settings, permission: "settings.view" },
  { label: "Activity Logs", path: "/admin/activity", icon: Activity, permission: "activity.view" },
];
